### ISSUE TITLE
Wifi Setup page doesn't show in web browser

### ISSUE THREAD

**Issue by ansgar75** [Lymkin/ESP8226_Garage_Controller#1]
Hi,
I would like to use your project.

Unfortunately there is just a blank webpage after I connected to the WIFI of the ESP and browsed to 192.168.4.1

Do you have an idea what I made wrong.

ESP is a NODE MCU 0.9 with 4M
I tried to connect with my Iphone 7. Safari web browser.

... this is what serial monitor says

8:07:50.897 -> Garage Opener 1.0
18:07:50.897 -> Starting ESP8266 AsyncWebServer
18:07:50.897 -> SPIFFS opened: FAIL
18:07:50.930 -> WiFi config not set/found
18:07:50.930 -> General config applied
18:07:51.097 -> Wait for WiFi connection.
18:07:59.912 -> Cannot connect to: MYSSID
18:07:59.981 -> Can not connect to WiFi station. Go into AP mode.
18:07:59.981 -> Soft AP started IP address: 192.168.4.1
18:07:59.981 -> ESP8266 AsyncWebServer Startup Complete
18:08:00.083 -> Starting Scan for WiFi Networks......
18:08:00.083 -> 12:00:09 AM
18:08:00.083 -> WiFi AP Mode....Auto restart in 5 minutes.
18:08:00.083 -> Initializing, Please wait......
18:08:02.255 -> scandone
18:08:05.087 -> System Online
18:08:05.320 -> add 1
18:08:05.320 -> aid 1
18:08:05.320 -> station: c8:69:cd:9c:50:f2 join, AID = 1
18:08:06.399 -> handleFileRead: /hotspot-detect.html
18:08:06.399 -> isAdmin request from - 192.168.4.100
18:08:08.016 -> handleFileRead: /bag
18:08:08.016 -> isAdmin request from - 192.168.4.100
18:08:09.056 -> handleFileRead: /bag
18:08:09.056 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> handleFileRead: /
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> handleFileRead: /
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> handleFileRead: /
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:10.235 -> handleFileRead: /bag
18:08:10.235 -> isAdmin request from - 192.168.4.100
18:08:11.258 -> handleFileRead: /bag
18:08:11.258 -> isAdmin request from - 192.168.4.100
18:08:15.415 -> handleFileRead: /bag
18:08:15.415 -> isAdmin request from - 192.168.4.100
18:08:19.017 -> handleFileRead: /bag
18:08:19.017 -> isAdmin request from - 192.168.4.100
18:08:27.134 -> handleFileRead: /bag
18:08:27.134 -> isAdmin request from - 192.168.4.100
18:08:28.323 -> handleFileRead: /bag
18:08:28.323 -> isAdmin request from - 192.168.4.100
18:08:38.370 -> handleFileRead: /bag
18:08:38.370 -> isAdmin request from - 192.168.4.100
18:08:39.415 -> handleFileRead: /bag
18:08:39.415 -> isAdmin request from - 192.168.4.100
18:08:53.486 -> handleFileRead: /
18:08:53.486 -> isAdmin request from - 192.168.4.100
18:08:53.486 -> isAdmin request from - 192.168.4.100
18:08:55.435 -> handleFileRead: /bag
18:08:55.435 -> isAdmin request from - 192.168.4.100
18:08:56.480 -> handleFileRead: /bag
18:08:56.480 -> isAdmin request from - 192.168.4.100
18:09:27.527 -> handleFileRead: /bag
18:09:27.527 -> isAdmin request from - 192.168.4.100
18:09:28.604 -> handleFileRead: /bag
18:09:28.604 -> isAdmin request from - 192.168.4.100

In Chrome on my MacBook it says "Page not found" while browsing to 192.168.4.1
Wifi is connectet to the ESP.

Thanks for your help
Ansgar

**Comment by ansgar75** [comment]
... this is what serial monitor says

8:07:50.897 -> Garage Opener 1.0
18:07:50.897 -> Starting ESP8266 AsyncWebServer
18:07:50.897 -> SPIFFS opened: FAIL
18:07:50.930 -> WiFi config not set/found
18:07:50.930 -> General config applied
18:07:51.097 -> Wait for WiFi connection.
18:07:59.912 -> Cannot connect to: MYSSID
18:07:59.981 -> Can not connect to WiFi station. Go into AP mode.
18:07:59.981 -> Soft AP started IP address: 192.168.4.1
18:07:59.981 -> ESP8266 AsyncWebServer Startup Complete
18:08:00.083 -> Starting Scan for WiFi Networks......
18:08:00.083 -> 12:00:09 AM
18:08:00.083 -> WiFi AP Mode....Auto restart in 5 minutes.
18:08:00.083 -> Initializing, Please wait......
18:08:02.255 -> scandone
18:08:05.087 -> System Online
18:08:05.320 -> add 1
18:08:05.320 -> aid 1
18:08:05.320 -> station: c8:69:cd:9c:50:f2 join, AID = 1
18:08:06.399 -> handleFileRead: /hotspot-detect.html
18:08:06.399 -> isAdmin request from - 192.168.4.100
18:08:08.016 -> handleFileRead: /bag
18:08:08.016 -> isAdmin request from - 192.168.4.100
18:08:09.056 -> handleFileRead: /bag
18:08:09.056 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> handleFileRead: /
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> handleFileRead: /
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> handleFileRead: /
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:09.228 -> isAdmin request from - 192.168.4.100
18:08:10.235 -> handleFileRead: /bag
18:08:10.235 -> isAdmin request from - 192.168.4.100
18:08:11.258 -> handleFileRead: /bag
18:08:11.258 -> isAdmin request from - 192.168.4.100
18:08:15.415 -> handleFileRead: /bag
18:08:15.415 -> isAdmin request from - 192.168.4.100
18:08:19.017 -> handleFileRead: /bag
18:08:19.017 -> isAdmin request from - 192.168.4.100
18:08:27.134 -> handleFileRead: /bag
18:08:27.134 -> isAdmin request from - 192.168.4.100
18:08:28.323 -> handleFileRead: /bag
18:08:28.323 -> isAdmin request from - 192.168.4.100
18:08:38.370 -> handleFileRead: /bag
18:08:38.370 -> isAdmin request from - 192.168.4.100
18:08:39.415 -> handleFileRead: /bag
18:08:39.415 -> isAdmin request from - 192.168.4.100
18:08:53.486 -> handleFileRead: /
18:08:53.486 -> isAdmin request from - 192.168.4.100
18:08:53.486 -> isAdmin request from - 192.168.4.100
18:08:55.435 -> handleFileRead: /bag
18:08:55.435 -> isAdmin request from - 192.168.4.100
18:08:56.480 -> handleFileRead: /bag
18:08:56.480 -> isAdmin request from - 192.168.4.100
18:09:27.527 -> handleFileRead: /bag
18:09:27.527 -> isAdmin request from - 192.168.4.100
18:09:28.604 -> handleFileRead: /bag
18:09:28.604 -> isAdmin request from - 192.168.4.100


In Chrome on my MacBook it says "Page not found" while browsing to 192.168.4.1
Wifi is connectet to the ESP

**Comment by ansgar75** [comment]
Hi,

I found the problem.
In Arduino IDE I hat to take the correct build options. SPIFFS was off. Now I added SPIFFS 1M and it worked.

Thank you for your work
Ansgar

**Comment by Lymkin** [comment]
Glad you got it figured out.  I’m on holiday, so I haven’t been online much.
